"""Download or load EU ETS source CSVs.

Supports a live download mode and a deterministic local fallback. The local
fallback is generated by ``warehouse/seed/generate_sample.py`` and bundled
with the repo so the pipeline always runs end-to-end.
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
import requests
import structlog

log = structlog.get_logger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
SEED_DIR = REPO_ROOT / "warehouse" / "seed" / "data"


def _ensure_local_sample() -> None:
    """Generate the local sample if missing."""
    if not (SEED_DIR / "installations.csv").exists():
        from warehouse.seed.generate_sample import generate

        log.info("generating_local_sample", path=str(SEED_DIR))
        generate(SEED_DIR)


def _download(url: str, dest: Path) -> Path:
    """Download a CSV to ``dest`` with a 60s timeout."""
    log.info("downloading", url=url)
    resp = requests.get(url, timeout=60)
    resp.raise_for_status()
    dest.write_bytes(resp.content)
    return dest


def load_table(name: str) -> pd.DataFrame:
    """Load one of installations / emissions / allowances as a DataFrame.

    Args:
        name: Logical table name.

    Returns:
        DataFrame with raw, untyped columns.
    """
    if name not in {"installations", "emissions", "allowances"}:
        raise ValueError(f"unknown table: {name}")

    use_local = os.getenv("USE_LOCAL_FALLBACK", "true").lower() == "true"
    url = os.getenv(f"EUETS_{name.upper()}_URL")

    if not use_local and url:
        try:
            tmp = SEED_DIR / f"{name}.csv"
            SEED_DIR.mkdir(parents=True, exist_ok=True)
            _download(url, tmp)
        except Exception as exc:
            log.warning("download_failed_falling_back", error=str(exc))
            _ensure_local_sample()
    else:
        _ensure_local_sample()

    path = SEED_DIR / f"{name}.csv"
    log.info("loading_csv", path=str(path))
    return pd.read_csv(path, encoding="utf-8")


def load_country_codes() -> pd.DataFrame:
    """Load the bundled ISO 3166 country lookup."""
    return pd.read_csv(REPO_ROOT / "warehouse" / "seed" / "country_codes.csv")
